apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-ngx-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-ngx-broker
  template:
    metadata:
      labels:
        app: paperless-ngx-broker
    spec:
      containers:
        - name: broker
          image: redis:7
          volumeMounts:
            - mountPath: /data
              name: paperless-ngx-broker-pvc-redisdata
      volumes:
        - name: paperless-ngx-broker-pvc-redisdata
          persistentVolumeClaim:
            claimName: paperless-ngx-broker-pvc-redisdata